version = 0.1

[default.deploy]
[default.deploy.parameters]
stack_name = "MelomixT"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
resolve_s3 = true
s3_prefix = "MelomixT"
image_repositories = []
