AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Integradora9A

  Sample SAM Template for Integradora9A

Globals:
  Function:
    Timeout: 5
    MemorySize: 128

Resources:

  CreateUserFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: user_management/create_user/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        RegisterUser:
          Type: Api
          Properties:
            Path: /create_user
            Method: post
      Environment:
        Variables:
          RDS_HOST: "integradoramelomix.c92quiiw2jmr.us-east-2.rds.amazonaws.com"
          RDS_USER: "admin"
          RDS_PASSWORD: "admin123"
          RDS_DB: "integradoramelomix"

  ReadUserFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: user_management/read_user/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        GetUsers:
          Type: Api
          Properties:
            Path: /read_user
            Method: get
      Environment:
        Variables:
          RDS_HOST: "integradoramelomix.c92quiiw2jmr.us-east-2.rds.amazonaws.com"
          RDS_USER: "admin"
          RDS_PASSWORD: "admin123"
          RDS_DB: "integradoramelomix"

  UpdateUserFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: user_management/update_user/
      Handler: handler.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        UpdateUser:
          Type: Api
          Properties:
            Path: /update_user
            Method: put
      Environment:
        Variables:
          RDS_HOST: "integradoramelomix.c92quiiw2jmr.us-east-2.rds.amazonaws.com"
          RDS_USER: "admin"
          RDS_PASSWORD: "admin123"
          RDS_DB: "integradoramelomix"

  DeleteUserFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: user_management/delete_user/
      Handler: handler.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        DeleteUser:
          Type: Api
          Properties:
            Path: /delete_user
            Method: delete
      Environment:
        Variables:
          RDS_HOST: "integradoramelomix.c92quiiw2jmr.us-east-2.rds.amazonaws.com"
          RDS_USER: "admin"
          RDS_PASSWORD: "admin123"
          RDS_DB: "integradoramelomix"

Outputs:
  RegisterUserApi:
    Description: "API Gateway endpoint URL for Prod stage for Register User function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create_user/"
  GetUsersApi:
    Description: "API Gateway endpoint URL for Prod stage for Get Users function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/read_user/"
  UpdateUserApi:
    Description: "API Gateway endpoint URL for Prod stage for Update User function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/update_user/"
  DeleteUserApi:
    Description: "API Gateway endpoint URL for Prod stage for Delete User function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/delete_user/"
