import unittest
import songs_test.test_read_song as test_read_song
import songs_test.test_create_song as test_create_song
import songs_test.test_update_song as test_update_song
import songs_test.test_delete_song as test_delete_song

import admin_test.test_app_delete_admin as test_app_delete_admin
import admin_test.test_app_read_admin as test_app_read_admin
import admin_test.test_app_update_admin as test_app_update_admin
import admin_test.test_app_create_admin as test_app_create_admin

import albums_test.test_app_read_album as test_app_read_album
import albums_test.test_app_create_album as test_app_create_album
import albums_test.test_app_update_album as test_app_update_album
import albums_test.test_app_delete_album as test_app_delete_album

import artist_test.test_create_artist_app as test_create_artist_app
import artist_test.test_read_artist_app as test_read_artist_app
import artist_test.test_update_artist_app as test_update_artist_app
import artist_test.test_delete_artist_app as test_delete_artist_app
import artist_test.test_read_all_artist_app as test_read_all_artist_app

import favorite_on_use_managment_test.test_create_favorite_on_use as test_create_favorite_on_use
import favorite_on_use_managment_test.test_read_favorite_on_use as test_read_favorite_on_use
import favorite_on_use_managment_test.test_update_favorite_on_use as test_update_favorite_on_use
import favorite_on_use_managment_test.test_delete_favorite_on_use as test_delete_favorite_on_use

import favorites_test.test_create_favorite as test_create_favorite
import favorites_test.test_read_favorite as test_read_favorite
import favorites_test.test_update_favorite as test_update_favorite
import favorites_test.test_delete_favorite as test_delete_favorite

import test_user.test_app_read_user as test_app_read_user
import test_user.test_app_create_user as test_app_create_user
import test_user.test_app_update_user as test_app_update_user
import test_user.test_app_delete_user as test_app_delete_user
import test_user.test_app_read_all_user as test_app_read_all_user

import test_app_login as test_app_login

loader = unittest.TestLoader()
suite = unittest.TestSuite()

suite.addTests(loader.loadTestsFromModule(test_read_song))
suite.addTests(loader.loadTestsFromModule(test_create_song))
suite.addTests(loader.loadTestsFromModule(test_delete_song))
suite.addTests(loader.loadTestsFromModule(test_update_song))

suite.addTests(loader.loadTestsFromModule(test_app_create_admin))
suite.addTests(loader.loadTestsFromModule(test_app_read_admin))
suite.addTests(loader.loadTestsFromModule(test_app_update_admin))
suite.addTests(loader.loadTestsFromModule(test_app_delete_admin))

suite.addTests(loader.loadTestsFromModule(test_app_read_album))
suite.addTests(loader.loadTestsFromModule(test_app_create_album))
suite.addTests(loader.loadTestsFromModule(test_app_update_album))
suite.addTests(loader.loadTestsFromModule(test_app_delete_album))

suite.addTests(loader.loadTestsFromModule(test_create_artist_app))
suite.addTests(loader.loadTestsFromModule(test_read_artist_app))
suite.addTests(loader.loadTestsFromModule(test_update_artist_app))
suite.addTests(loader.loadTestsFromModule(test_delete_artist_app))
suite.addTests(loader.loadTestsFromModule(test_read_all_artist_app))

suite.addTests(loader.loadTestsFromModule(test_create_favorite_on_use))
suite.addTests(loader.loadTestsFromModule(test_read_favorite_on_use))
suite.addTests(loader.loadTestsFromModule(test_update_favorite_on_use))
suite.addTests(loader.loadTestsFromModule(test_delete_favorite_on_use))

suite.addTests(loader.loadTestsFromModule(test_create_favorite))
suite.addTests(loader.loadTestsFromModule(test_read_favorite))
suite.addTests(loader.loadTestsFromModule(test_update_favorite))
suite.addTests(loader.loadTestsFromModule(test_delete_favorite))

suite.addTests(loader.loadTestsFromModule(test_app_read_user))
suite.addTests(loader.loadTestsFromModule(test_app_create_user))
suite.addTests(loader.loadTestsFromModule(test_app_update_user))
suite.addTests(loader.loadTestsFromModule(test_app_delete_user))
suite.addTests(loader.loadTestsFromModule(test_app_read_all_user))

suite.addTests(loader.loadTestsFromModule(test_app_login))

runner = unittest.TextTestRunner(verbosity=3)
runner.run(suite)