name: Deploy to AWS Lambda

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        function:
          - name: create_favorite
            path: favorites_managment/create_favorite
            requirements: favorites_managment/create_favorite/requirements.txt
            function_name: YOUR_CREATE_FAVORITE_LAMBDA_FUNCTION_NAME
          - name: delete_favorite
            path: favorites_managment/delete_favorite
            requirements: favorites_managment/delete_favorite/requirements.txt
            function_name: YOUR_DELETE_FAVORITE_LAMBDA_FUNCTION_NAME
          - name: read_favorite
            path: favorites_managment/read_favorite
            requirements: favorites_managment/read_favorite/requirements.txt
            function_name: YOUR_READ_FAVORITE_LAMBDA_FUNCTION_NAME
          - name: update_favorite
            path: favorites_managment/update_favorite
            requirements: favorites_managment/update_favorite/requirements.txt
            function_name: YOUR_UPDATE_FAVORITE_LAMBDA_FUNCTION_NAME
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}  # Optional

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify your Python version

      - name: Install dependencies
        run: |
          cd ${{ matrix.function.path }}
          python -m pip install --upgrade pip
          if [ -f ${{ matrix.function.requirements }} ]; then pip install -r ${{ matrix.function.requirements }}; fi

      - name: Package application
        run: |
          cd ${{ matrix.function.path }}
          zip -r ../${{ matrix.function.name }}-deployment-package.zip .

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code --function-name ${{ matrix.function.function_name }} --zip-file fileb://${{ matrix.function.name }}-deployment-package.zip
